# password: inoatachelutu

[accounts.wallet_10]
mnemonic = "athlete nothing pilot stem limb dream amazing glove gasp you key digital process glad thought border type donate slow index unlock say tribe oak"
balance = 100_000_000_000_000
# stx_address: ST02D2KP0630FS1BCJ7YM4TYMDH6NS9QKR0B57R3

[accounts.wallet_11]
mnemonic = "tilt call borrow know mail consider fall tomorrow lonely repair picnic cotton barrel negative almost school able giggle step tooth also kite hint snack"
balance = 100_000_000_000_000
# stx_address: ST109H2F95ZKHDKW4G7DQSCV6ZRXJD9EA126HH4E1

[accounts.wallet_12]
mnemonic = "canal brown prefer parent fiscal physical lunar erosion spider athlete chat text weird ecology ski pear crazy pride equip uniform misery pizza unveil milk"
balance = 100_000_000_000_000
# stx_address: ST1T1XCR5RJ9NBFVMVAKWJDZ14M4RT9WJNNAK1A8Z

[accounts.wallet_13]
mnemonic = "anxiety bid oyster seven horn stomach genius logic snow pizza view degree toe close fortune reform heavy gym notable spin bicycle drop ignore soccer"
balance = 100_000_000_000_000
# stx_address: ST188NGMBNCVSHJRAY1P7MWP33R90986628T02GPF

[accounts.wallet_14]
mnemonic = "staff canoe rabbit record fruit finger electric rhythm group cake mixture peanut van girl wolf tornado thought purchase roast various scorpion virtual banana shed"
balance = 100_000_000_000_000
# stx_address: ST1SFEXNZCY6GGQBZ9GWAC5Q6RX3GJBE970ZPBWPZ

[accounts.wallet_15]
mnemonic = "never urban grass weekend duck palm sock discover flush equip grid alien mechanic suffer affair monkey timber luggage wrong energy soap swap jeans clog"
balance = 100_000_000_000_000
# stx_address: ST24V6BD6K9H0F38NZ60BKVS4B813AT5YZ01RV8C4

[accounts.wallet_16]
mnemonic = "move either zebra half swamp fashion museum salad finish fantasy risk antique melt despair crumble uncover stomach ahead fiction judge umbrella pill child tail"
balance = 100_000_000_000_000
# stx_address: ST2APY5MERZWF8WAE4CGYXX330M2AHE4SYNN8JH86

[accounts.wallet_17]
mnemonic = "easy cruise kiss horror fever capable merry exit quote equal board swap rapid document click boil stamp conduct prepare garbage skate volume hub key"
balance = 100_000_000_000_000
# stx_address: ST205976S0WM7PYFNJJJVXHXZSSKZKRYHVMG5N4P5

[accounts.wallet_18]
mnemonic = "decide wrap denial buzz umbrella rich evoke tell speak sister stadium fault sibling brown attitude write rib sudden beauty mosquito despair inform risk region"
balance = 100_000_000_000_000
# stx_address: ST27PW6DS6X3ZY2TES5DNFRBVQJK4ZRF5G6RVFTF2

[accounts.wallet_19]
mnemonic = "churn wall sugar soda stadium limb run nut retreat truck trouble million era option kind garden blouse suit metal shadow ramp mercy put grain"
balance = 100_000_000_000_000
# stx_address: STVC5SGS8FYH64WWDAE5NQMVVD060TTM7PEFM483