[accounts.deployer]
address = "ST02D2KP0630FS1BCJ7YM4TYMDH6NS9QKR0B57R3"
mnemonic = "athlete nothing pilot stem limb dream amazing glove gasp you key digital process glad thought border type donate slow index unlock say tribe oak"
privateKey = "c2eae79ad466a0a98d64e24fc27d0a8eaf75891c9029d5f821a67743affa874201"
publicKey = "0257f48a1505f05acc1ff4e5cf274f248f9ca736f6da87ea7b06d479d80218db86"
btcAddress = "mfXkTvKbVP56WkxDDfnaeK17kgxvfgcsUJ"

[accounts.wallet_1]
address = "ST109H2F95ZKHDKW4G7DQSCV6ZRXJD9EA126HH4E1"
mnemonic = "tilt call borrow know mail consider fall tomorrow lonely repair picnic cotton barrel negative almost school able giggle step tooth also kite hint snack"
privateKey = "811ad2e8f9bafb837c6f7df8521d71a2782b19701715b511018eaa93c3ed84da01"
publicKey = "028d07dbcbeafbc06d3d8ac2afeb7cde16476ca39af8de1a5c34ce723ecc6237ec"
btcAddress = "mmQWGuYu1558ivmLQ5mfMoUrEnj8468sFz"

[accounts.wallet_2]
address = "ST1T1XCR5RJ9NBFVMVAKWJDZ14M4RT9WJNNAK1A8Z"
mnemonic = "canal brown prefer parent fiscal physical lunar erosion spider athlete chat text weird ecology ski pear crazy pride equip uniform misery pizza unveil milk"
privateKey = "5bfaefc764eb822296d21fc1ff36ff88c59c62419baa5c5cfb90194cd84af8e801"
publicKey = "031fa2fa8dfc032d599209719c6d6e106e5d68dba36b046b1b5545e73eca7471bd"
btcAddress = "mr6wTLBgV7gV9AsJqcrm5y6qhT3NQc6S63"

[accounts.wallet_3]
address = "ST188NGMBNCVSHJRAY1P7MWP33R90986628T02GPF"
mnemonic = "anxiety bid oyster seven horn stomach genius logic snow pizza view degree toe close fortune reform heavy gym notable spin bicycle drop ignore soccer"
privateKey = "17ebd9a02291e3c4f54a953d16bc14442ea5ed82a06de290d44c9580394e5d4a01"
publicKey = "024cc84f61a94815f04e1ff6fa478a2a3b90062eea947157d130a71036b6c9f0f2"
btcAddress = "mnrpacMWpCR4zen8WipKpxvpMBSkhiDmPS"

[accounts.wallet_4]
address = "ST1SFEXNZCY6GGQBZ9GWAC5Q6RX3GJBE970ZPBWPZ"
mnemonic = "staff canoe rabbit record fruit finger electric rhythm group cake mixture peanut van girl wolf tornado thought purchase roast various scorpion virtual banana shed"
privateKey = "d9f2a56bca9a04f65893f56082eac520b459acae3c8908a1b8bec0d560d25c3b01"
publicKey = "035aa0ff12cf3d4c010133a08956fb40be4b9decbaef20b564e2b4f54d0a272003"
btcAddress = "mqzqn1hvg8ytcAdVc4nduSuPwAMyQQyPKy"

[accounts.wallet_5]
address = "ST24V6BD6K9H0F38NZ60BKVS4B813AT5YZ01RV8C4"
mnemonic = "never urban grass weekend duck palm sock discover flush equip grid alien mechanic suffer affair monkey timber luggage wrong energy soap swap jeans clog"
privateKey = "74c238bd1223dee72fd0e65bbd65c0a8eaab6c951c817dc43d5ae924920453b101"
publicKey = "03305348ed9e9f8da4e0e750fe89cc2794776c8c3a8bbd6751d62e188dd1963c6a"
btcAddress = "mt53Ws1ELkiFwjYSa2To9jAXFY65YStuvW"

[accounts.wallet_6]
address = "ST2APY5MERZWF8WAE4CGYXX330M2AHE4SYNN8JH86"
mnemonic = "move either zebra half swamp fashion museum salad finish fantasy risk antique melt despair crumble uncover stomach ahead fiction judge umbrella pill child tail"
privateKey = "ccd740651417e5a0a57f538798f29656fd4219695e068e8b440c5f51137cf59301"
publicKey = "03bf36b25a7709eddc0f30b8762dda12d851c631c33ace06877cdabb1649961c6d"
btcAddress = "mu964B4sGt8A5hwoJSabSSeYAeNnvPMiAJ"

[accounts.wallet_7]
address = "ST205976S0WM7PYFNJJJVXHXZSSKZKRYHVMG5N4P5"
mnemonic = "easy cruise kiss horror fever capable merry exit quote equal board swap rapid document click boil stamp conduct prepare garbage skate volume hub key"
privateKey = "00c992ea87d8672ce4275d47ce03df3364bf079029f1968ef1b3f7877bcae28401"
publicKey = "03a175655844ed71dedd443387f779ad458dacd4d6a0b680049d6a251140750843"
btcAddress = "msDW9boVarRuj97Erm3QgPyLYL7snr4z5d"

[accounts.wallet_8]
address = "ST27PW6DS6X3ZY2TES5DNFRBVQJK4ZRF5G6RVFTF2"
mnemonic = "decide wrap denial buzz umbrella rich evoke tell speak sister stadium fault sibling brown attitude write rib sudden beauty mosquito despair inform risk region"
privateKey = "6facfac166fc8d7c7d0fa2a4d859b339b11ed4159c2d27bc91980d814cf165ec01"
publicKey = "036a66a2c14d190f7bcc43a39329ee18b9b1c34b7552c178a54c0ab55bdeedeb69"
btcAddress = "mtbLpQEZwk8MykRhWZvAqiEh3HaerUzPCg"

[accounts.wallet_9]
address = "STVC5SGS8FYH64WWDAE5NQMVVD060TTM7PEFM483"
mnemonic = "churn wall sugar soda stadium limb run nut retreat truck trouble million era option kind garden blouse suit metal shadow ramp mercy put grain"
privateKey = "94e86c22b1d02893d51f43fd726881ef2cb15f69e6be8b2a01f0eb2f0b6bb44901"
publicKey = "02ed3371ac7240751a8d2ffe082f4949a65c793c20fa0d572f650127e466f71578"
btcAddress = "mkWWGDjz7xvBgB8vQjMABMPrUTbx9RbEu5"